title: Sanyam Raheja
logo: /Users/samcons/Downloads/sam.jpeg
description: I am a data analyst learning about AI/ML in order to become an AI Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
