title: Sanyam Raheja
logo: /assets/img/logo.png
description: I am a data analyst learning about AI/ML in order to become an AI Engineer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
